name: dbt_demo

profile: dbt_demo

seed-paths: ["seeds"]
test-paths: ["tests"]
# Chúng ta có thể thêm cả các thư mục khác ["models", "data_sources"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_demo:
    +materialized: "{{ 'table' if target.name == 'test' else 'view' }}"
    staging: #subfolder of models
      +schema: "{{ 'iceberg_staging.staging' if target.name == 'test' else 'staging' }}"
      +file_format: iceberg
    intermediate: #subfolder of models
      +schema: "{{ 'iceberg_int.intermediate' if target.name == 'test' else 'intermediate' }}"
      +file_format: iceberg
    marts: #subfolder of models
      +materialized: table
      +schema: marts
