# tên "dbt_demo" phải khớp với tên trong dbt_project.yml
dbt_demo:
  target: test
  outputs:           
    test:
      type: spark
      method: session
      host: spark-connect-placeholder # để vào cho đỡ bị lỗi là chính, ko cần fill in vào
      schema: test
      threads: 4
      server_side_parameters:
        spark.sql.catalog.iceberg_staging: org.apache.iceberg.spark.SparkCatalog
        spark.sql.catalog.iceberg_staging.type: glue
        spark.sql.catalog.iceberg_staging.glue.endpoint: "{{ env_var('DDPE_GLUE_ENDPOINT') }}"
        spark.sql.catalog.iceberg_staging.glue.id: "{{ env_var('DDPE_STAGING_GLUE_ID') }}"
        spark.sql.catalog.iceberg_staging.warehouse: "{{ env_var('DDPE_ICEBERG_STAGING_WAREHOUSE') }}"
        spark.sql.catalog.iceberg_staging.client.region: "{{ env_var('DDPE_GLUE_REGION', 'us-east-1') }}"
        spark.sql.catalog.iceberg_staging.s3.endpoint: "{{ env_var('DDPE_ICEBERG_STAGING_S3_ENDPOINT') }}"
        spark.sql.catalog.iceberg_staging.s3.access-key-id: "{{ env_var('DDPE_S3_STAGING_ACCESS_KEY') }}"
        spark.sql.catalog.iceberg_staging.s3.secret-access-key: "{{ env_var('DDPE_S3_STAGING_SECRET_KEY') }}"
        spark.sql.catalog.iceberg_staging.s3.path-style-access: "true"

        spark.sql.catalog.iceberg_int: org.apache.iceberg.spark.SparkCatalog
        spark.sql.catalog.iceberg_int.type: glue
        spark.sql.catalog.iceberg_int.glue.endpoint: "{{ env_var('DDPE_GLUE_ENDPOINT') }}"
        spark.sql.catalog.iceberg_int.glue.id: "{{ env_var('DDPE_INTERMEDIATE_GLUE_ID') }}"
        spark.sql.catalog.iceberg_int.warehouse: "{{ env_var('DDPE_ICEBERG_INTERMEDIATE_WAREHOUSE') }}"
        spark.sql.catalog.iceberg_int.client.region: "{{ env_var('DDPE_GLUE_REGION', 'us-east-1') }}"
        spark.sql.catalog.iceberg_int.s3.endpoint: "{{ env_var('DDPE_ICEBERG_INTERMEDIATE_S3_ENDPOINT') }}"
        spark.sql.catalog.iceberg_int.s3.access-key-id: "{{ env_var('DDPE_S3_INTERMEDIATE_ACCESS_KEY') }}"
        spark.sql.catalog.iceberg_int.s3.secret-access-key: "{{ env_var('DDPE_S3_INTERMEDIATE_SECRET_KEY') }}"
        spark.sql.catalog.iceberg_int.s3.path-style-access: "true"
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_PROD_HOST', 'your-postgres-prod-host') }}"
      user: "{{ env_var('POSTGRES_PROD_USER', 'dbt_user') }}"
      password: "{{ env_var('POSTGRES_PROD_PASSWORD', '') }}"
      port: 6543
      dbname: postgres
      schema: prod
      threads: 4
