version: 2

sources:
#########################################################################################################################
  - name: postgres
    description: "Dữ liệu nguồn thô từ PostgreSQL database"
    schema: public # mặc định nếu không khai báo schema trong source thì dbt sẽ lấy tên source làm schema (postgres)
    config:
      enabled: "{{ target.name != 'test' }}"
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments

#########################################################################################################################
  - name: iceberg
    description: "Raw data dạng Iceberg trên Spark"
    schema: iceberg_staging.source_data
    config:
      enabled: "{{ target.name == 'test' }}"

    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments
#########################################################################################################################
