version: 2

sources:
#########################################################################################################################
  - name: postgres
    description: "Dữ liệu nguồn thô từ PostgreSQL database"
    schema: public # mặc định nếu không khai báo schema trong source thì dbt sẽ lấy tên source làm schema (postgres)
    config:
      enabled: "{{ target.name != 'test' }}"
    tables:
      - name: raw_customers
        description: "Bảng chứa thông tin thô của khách hàng"
        columns:
          - name: id
            description: "Mã ID khách hàng"
            data_tests:
              - unique
              - not_null
          - name: first_name
            description: "Tên"
          - name: last_name
            description: "Họ"

      - name: raw_orders
        description: "Bảng chứa thông tin thô của đơn hàng"
        columns:
          - name: id
            description: "Mã ID đơn hàng"
            data_tests:
              - unique
              - not_null
          - name: user_id
            description: "Mã ID người dùng đặt hàng"
            data_tests:
              - not_null
              - relationships:
                  to: source('postgres', 'raw_customers')
                  field: id
                  config:
                    severity: warn
          - name: order_date
            description: "Ngày đặt hàng"
          - name: status
            description: "Trạng thái đơn hàng"
            data_tests:
              - accepted_values:
                  values: ['completed', 'returned', 'pending', 'shipped']

      - name: raw_payments
        description: "Bảng chứa thông tin thô của thanh toán"
        columns:
          - name: id
            description: "Mã ID giao dịch thanh toán"
            data_tests:
              - unique
              - not_null
          - name: order_id
            description: "Mã ID đơn hàng liên quan"
            data_tests:
              - not_null
              - relationships:
                  to: source('postgres', 'raw_orders')
                  field: id
          - name: payment_method
            description: "Phương thức thanh toán"
            data_tests:
              - accepted_values:
                  values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
          - name: amount
            description: "Số tiền thanh toán (tính theo cent)"

#########################################################################################################################
  - name: iceberg
    description: "Raw data dạng Iceberg trên Spark"
    schema: source_data
    config:
      enabled: "{{ target.name == 'test' }}"

    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments
#########################################################################################################################
